-- scripts/ledger-rows-0010-0012.sql
-- GENERATED by scripts/poc-free/build-ledger-rows.mjs. Do not hand-edit.
-- Regenerate with:  node scripts/poc-free/build-ledger-rows.mjs
-- Verify with:      node scripts/poc-free/build-ledger-rows.mjs --check
--
-- Card P2-19. The three schema_migrations rows that were never written.
--
-- THIS FILE CHANGES NO SCHEMA. It writes three rows into Supabase's own
-- bookkeeping table, supabase_migrations.schema_migrations, whose newest row is
-- 0009 while the database itself is at 0012. Every column, constraint, function,
-- policy and grant described by 0010, 0011 and 0012 is already in place and
-- journalled in docs/migrations/APPLY-LOG.md. What is missing is the record.
--
-- WHY IT MATTERS: anything that reads that ledger to decide what is pending
-- (supabase db push, a future CLI-driven apply, or a human asking "what is
-- applied?") concludes that 0010, 0011 and 0012 are still to come, and tries to
-- run them again.
--
-- IT CONTAINS NO DROP, NO TRUNCATE AND NO DELETE. Three INSERTs, each
-- ON CONFLICT DO NOTHING, so running it twice is not an error and running it
-- after someone else has already done it is not an error either.
--
-- IT IS WRAPPED SO IT CAN BE INSPECTED BEFORE IT COMMITS. The transaction is
-- opened here and NOT closed. Read the RETURNING output, then send COMMIT; or
-- ROLLBACK; yourself. A file that commits on your behalf is a file you cannot
-- change your mind about.

begin;

-- Phase 1, pre-check. What the ledger holds BEFORE anything is written.
-- Expect the newest version to be 0010 or lower. If 0010, 0011 and 0012 are
-- already listed, someone has run this: send ROLLBACK; and stop.
select version, name from supabase_migrations.schema_migrations order by version;
select count(*) as ledger_rows_before from supabase_migrations.schema_migrations;

-- Phase 2, apply. 0010, confirm_extraction_draft, 7157 characters of SQL.
insert into supabase_migrations.schema_migrations (version, name, statements)
values ('0010', 'confirm_extraction_draft', array[$mig$-- 0010_confirm_extraction_draft.sql
-- RC Inventory phase 2, card P2-09. Confirming a reviewed extraction draft.
--
-- Runs as one transaction. Contains no DROP, no TRUNCATE and no DELETE.
--
-- THE AMBIGUITY MIGRATION 0008 DEFERRED IS SETTLED HERE, DELIBERATELY.
--
-- 0008's header recorded it in full: extraction_drafts.order_id carries no
-- foreign key because P2-08a's upload lane attaches a document to an inbound
-- order that already exists, so the value happens to be an inbound_orders.id,
-- while P2-09's acceptance says confirm CREATES the real inbound order, which
-- reads the other way. 0008 refused to settle it by accident. This file settles
-- it on purpose:
--
--   order_id IS THE EXTRACTION IDEMPOTENCY KEY AND NOTHING ELSE.
--
-- It is minted when a document enters the extraction lane and it names an
-- extraction, never an order. A draft becomes an order at confirm, and the
-- order it became is recorded on the draft in confirmed_inbound_order_id.
--
-- A draft whose order_id already names an existing inbound_orders row came from
-- the OTHER lane: the operator typed the order first and attached the document
-- to it. That order exists, so there is nothing to confirm, and the review list
-- excludes those rows rather than offering to create a duplicate.
--
-- "CONSUMED" IS MARKED, NOT DELETED, AND THAT IS THE STRONGER READING.
--
-- The card says the draft is consumed rather than left behind. Deleting it
-- would satisfy the sentence and destroy the evidence: _meta exists so that a
-- wrong extraction can be explained rather than argued about, and an extraction
-- deleted at the moment it turned into stock is exactly the one anybody would
-- later want to read. A consumed draft leaves the review list, points at the
-- order it became, and cannot be confirmed a second time. Nothing is left
-- behind and nothing is thrown away.
--
-- It also keeps this file free of a DELETE statement, which CLAUDE.md 8.6 would
-- otherwise make un-appliable without an owner sitting in front of it.

begin;

-- ===========================================================================
-- 1. WHAT A CONSUMED DRAFT CARRIES
-- ===========================================================================

alter table public.extraction_drafts
  add column confirmed_inbound_order_id uuid
    references public.inbound_orders (id) on delete set null,
  add column confirmed_at timestamptz,
  add column confirmed_by uuid references auth.users (id) on delete set null;

-- Every foreign key gets an index on the referencing side, same rule as 0001.
create index extraction_drafts_confirmed_order_idx
  on public.extraction_drafts (confirmed_inbound_order_id);

-- The two fields move together or the row is lying about its own history.
alter table public.extraction_drafts
  add constraint extraction_drafts_confirmed_pair check (
    (confirmed_inbound_order_id is null and confirmed_at is null)
    or (confirmed_inbound_order_id is not null and confirmed_at is not null)
  );

comment on column public.extraction_drafts.confirmed_inbound_order_id is
  'The inbound order this draft became, set at confirm. Null means the draft is still awaiting review. This column is what makes order_id purely an extraction key: the draft names the order it produced, the order never borrows the draft key.';


-- ===========================================================================
-- 2. CONFIRM, IN ONE TRANSACTION
-- ===========================================================================
--
-- Over PostgREST, creating the order, writing its lines, writing its first
-- history row and marking the draft consumed would be four calls and four
-- transactions. A failure between any two of them leaves a state the
-- application believes impossible: an order with no lines, or a draft that
-- produced an order nobody can find. Same reasoning as 0003.
--
-- SECURITY INVOKER, so RLS still decides who may write.

create or replace function public.confirm_extraction_draft(
  p_order_id      uuid,
  p_reference     text,
  p_supplier_name text,
  p_currency      public.currency_code,
  p_ordered_at    date,
  p_expected_at   date,
  p_total_mdl     numeric,
  p_lines         jsonb
)
returns uuid
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_draft      public.extraction_drafts%rowtype;
  v_order_id   uuid;
  v_line_count int;
begin
  if p_lines is null or jsonb_array_length(p_lines) = 0 then
    raise exception 'Comanda trebuie să aibă cel puțin o poziție.' using errcode = 'P0001';
  end if;

  -- FOR UPDATE serialises two operators pressing confirm at the same moment.
  -- The second waits, then sees confirmed_inbound_order_id set and refuses.
  select * into v_draft
  from public.extraction_drafts
  where order_id = p_order_id
  for update;

  if not found then
    raise exception 'Ciorna nu mai există.' using errcode = 'P0002';
  end if;

  if v_draft.confirmed_inbound_order_id is not null then
    raise exception 'Ciorna a fost deja confirmată.' using errcode = 'P0002';
  end if;

  if v_draft.status is null or v_draft.status = 'failed' then
    raise exception 'Documentul nu are date extrase de confirmat.' using errcode = 'P0001';
  end if;

  insert into public.inbound_orders
    (reference, supplier_name, currency, ordered_at, expected_at, total_mdl, status, created_by,
     document_path, document_uploaded_at)
  values
    (p_reference, p_supplier_name, p_currency, p_ordered_at, p_expected_at,
     coalesce(p_total_mdl, 0), 'pending_arrival', auth.uid(),
     v_draft.document_path, v_draft.callback_at)
  returning id into v_order_id;

  insert into public.order_lines (inbound_order_id, product_id, quantity, unit_price)
  select
    v_order_id,
    (line ->> 'product_id')::uuid,
    (line ->> 'quantity')::numeric,
    nullif(line ->> 'unit_price', '')::numeric
  from jsonb_array_elements(p_lines) as line;

  get diagnostics v_line_count = row_count;
  if v_line_count = 0 then
    raise exception 'Comanda trebuie să aibă cel puțin o poziție.' using errcode = 'P0001';
  end if;

  -- Same rule as 0003: the first status change writes history too, and the note
  -- says where the order came from, because an order created from a document is
  -- a different provenance from one typed by hand.
  insert into public.status_history
    (entity_type, entity_id, from_status, to_status, note, changed_by)
  values
    ('inbound_order', v_order_id, null, 'pending_arrival',
     'Comandă creată din document extras automat, verificat de operator.', auth.uid());

  update public.extraction_drafts
     set confirmed_inbound_order_id = v_order_id,
         confirmed_at               = now(),
         confirmed_by               = auth.uid()
   where order_id = p_order_id;

  return v_order_id;
end;
$$;

comment on function public.confirm_extraction_draft is
  'Turns a reviewed extraction draft into a real inbound order: the order, its lines, its first status_history row and the draft being marked consumed, all in one transaction. SECURITY INVOKER: RLS still applies. Refuses a draft already confirmed and a draft with nothing extracted.';

commit;
$mig$])
on conflict (version) do nothing
returning version, name;

-- Phase 2, apply. 0011, extraction_confirm_corrections, 11083 characters of SQL.
insert into supabase_migrations.schema_migrations (version, name, statements)
values ('0011', 'extraction_confirm_corrections', array[$mig$-- 0011_extraction_confirm_corrections.sql
-- RC Inventory phase 2, card P2-09. Two corrections to 0010.
--
-- Applied by EXECUTOR under ruling R-012. Runs as one transaction.
-- Contains no DROP TABLE, no TRUNCATE and no DELETE.
--
-- ONE NEAR-MISS, NAMED RATHER THAN BURIED: this file contains a
-- `drop constraint`. CLAUDE.md 8.6 names three statements that are never
-- auto-applied, `DROP TABLE`, `TRUNCATE` and `DELETE`, and a constraint drop is
-- none of them: it removes a CHECK expression and no row. It is called out here
-- and in the PR so the owner can rule otherwise if he reads the rule wider than
-- it is written. Relaxing a CHECK cannot be done any other way; a constraint is
-- replaced, never edited.
--
-- ===========================================================================
-- CORRECTION 1: A REFERENTIAL ACTION COULD BREAK 0010's OWN CHECK CONSTRAINT
-- ===========================================================================
--
-- 0010 added three columns and this constraint:
--
--     check ((confirmed_inbound_order_id is null and confirmed_at is null)
--         or (confirmed_inbound_order_id is not null and confirmed_at is not null))
--
-- The intent was right: a row must not claim to have produced an order without
-- saying when. The expression is wrong, because the column it constrains can be
-- changed by something other than the application. `confirmed_inbound_order_id`
-- carries `on delete set null`, so deleting an inbound order NULLs the column
-- on every draft pointing at it while `confirmed_at` stays. That is a row the
-- constraint calls impossible, so the delete fails with 23514 and takes its
-- whole transaction with it.
--
-- THIS IS NOT HYPOTHETICAL. `scripts/reset-test-data.sql`, which P2-15 hands to
-- the owner to run against production before the first real data, deletes from
-- `public.inbound_orders`. Once any draft has been confirmed against an order
-- in that set, the reset would have rolled back on a check violation, in the
-- SQL editor, with the owner watching, and the file is parsed rather than
-- executed in CI so nothing would have caught it first.
--
-- The corrected expression keeps the whole of the intent and survives the
-- referential action: a row that names an order must carry a time, and a row
-- whose order was deleted keeps the time, which is honest. The draft WAS
-- confirmed. The order it became is gone.
--
-- ===========================================================================
-- CORRECTION 2: confirmed_at IS THE FACT, THE FOREIGN KEY IS ONLY A POINTER
-- ===========================================================================
--
-- For the same reason, "has this draft been confirmed" must not be asked of a
-- column a delete elsewhere can null. 0010's function guarded on
-- `confirmed_inbound_order_id is not null`, and the review list filtered on the
-- same column. After an order deletion the draft would have reappeared in the
-- review list and could have been confirmed a second time, minting a second
-- order from one document, which is exactly the duplicate the whole idempotency
-- design exists to prevent. Both now read `confirmed_at`, which nothing but a
-- confirm ever writes.
--
-- ===========================================================================
-- CORRECTION 3: THE FUNCTION WAS EXECUTABLE BY anon, THROUGH PUBLIC
-- ===========================================================================
--
-- Same class as the defect 0009 corrected on 0008's tables, arriving through a
-- different door. 0008 left `anon` holding SELECT because Supabase grants at
-- CREATE TABLE time. 0010 left `anon` holding EXECUTE because PostgreSQL grants
-- EXECUTE to `PUBLIC` at CREATE FUNCTION time, and `anon` is a member of
-- `PUBLIC`. 0009's `alter default privileges ... revoke all on functions from
-- anon` does not close it: revoking from a role by name does not touch what
-- that role holds through PUBLIC.
--
-- Nothing was reachable. The function is SECURITY INVOKER, so an anonymous
-- caller running it would be refused by both the table grants (0009 revoked
-- them) and by RLS (every policy is `to authenticated`). As with 0008, the
-- missing layer was the first of two and the second was holding.
--
-- The durable fix is the same shape 0009 used: fix what exists, then change the
-- default so the next CREATE FUNCTION cannot reintroduce it. Every function in
-- this schema that is called from the application already carries an explicit
-- `grant execute ... to authenticated` (0001, 0003, 0004, 0006), and
-- `confirm_extraction_draft` is granted below, so removing PUBLIC's blanket
-- takes nothing away from anybody who is supposed to have it.
--
-- set_updated_at is the one function with no explicit grant, and it needs none:
-- it is a trigger function, and PostgreSQL checks EXECUTE on a trigger function
-- when the trigger is CREATED, not when it fires.

begin;

-- ===========================================================================
-- 1. THE CHECK CONSTRAINT, REPLACED
-- ===========================================================================

alter table public.extraction_drafts
  drop constraint extraction_drafts_confirmed_pair;

alter table public.extraction_drafts
  add constraint extraction_drafts_confirmed_pair check (
    confirmed_inbound_order_id is null or confirmed_at is not null
  );

comment on column public.extraction_drafts.confirmed_at is
  'When this draft was consumed into an inbound order. THIS is the fact that a draft has been confirmed, and nothing but a confirm ever writes it. confirmed_inbound_order_id is a pointer to the order and carries on delete set null, so it can become null again while this column stays; every check for "already confirmed" reads this one.';


-- ===========================================================================
-- 2. THE FUNCTION, WITH ITS GUARD READING confirmed_at
-- ===========================================================================
--
-- Replaced whole rather than patched, because a function is replaced by
-- definition and a reader should see the body that runs without holding two
-- files side by side. Everything except the guard is 0010's body unchanged.

create or replace function public.confirm_extraction_draft(
  p_order_id      uuid,
  p_reference     text,
  p_supplier_name text,
  p_currency      public.currency_code,
  p_ordered_at    date,
  p_expected_at   date,
  p_total_mdl     numeric,
  p_lines         jsonb
)
returns uuid
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_draft      public.extraction_drafts%rowtype;
  v_order_id   uuid;
  v_line_count int;
begin
  if p_lines is null or jsonb_array_length(p_lines) = 0 then
    raise exception 'Comanda trebuie să aibă cel puțin o poziție.' using errcode = 'P0001';
  end if;

  -- FOR UPDATE serialises two operators pressing confirm at the same moment.
  -- The second waits, then sees confirmed_at set and refuses.
  select * into v_draft
  from public.extraction_drafts
  where order_id = p_order_id
  for update;

  if not found then
    raise exception 'Ciorna nu mai există.' using errcode = 'P0002';
  end if;

  -- confirmed_at, not the foreign key. See the header, correction 2.
  if v_draft.confirmed_at is not null then
    raise exception 'Ciorna a fost deja confirmată.' using errcode = 'P0002';
  end if;

  if v_draft.status is null or v_draft.status = 'failed' then
    raise exception 'Documentul nu are date extrase de confirmat.' using errcode = 'P0001';
  end if;

  insert into public.inbound_orders
    (reference, supplier_name, currency, ordered_at, expected_at, total_mdl, status, created_by,
     document_path, document_uploaded_at)
  values
    (p_reference, p_supplier_name, p_currency, p_ordered_at, p_expected_at,
     coalesce(p_total_mdl, 0), 'pending_arrival', auth.uid(),
     v_draft.document_path, v_draft.callback_at)
  returning id into v_order_id;

  insert into public.order_lines (inbound_order_id, product_id, quantity, unit_price)
  select
    v_order_id,
    (line ->> 'product_id')::uuid,
    (line ->> 'quantity')::numeric,
    nullif(line ->> 'unit_price', '')::numeric
  from jsonb_array_elements(p_lines) as line;

  get diagnostics v_line_count = row_count;
  if v_line_count = 0 then
    raise exception 'Comanda trebuie să aibă cel puțin o poziție.' using errcode = 'P0001';
  end if;

  insert into public.status_history
    (entity_type, entity_id, from_status, to_status, note, changed_by)
  values
    ('inbound_order', v_order_id, null, 'pending_arrival',
     'Comandă creată din document extras automat, verificat de operator.', auth.uid());

  update public.extraction_drafts
     set confirmed_inbound_order_id = v_order_id,
         confirmed_at               = now(),
         confirmed_by               = auth.uid()
   where order_id = p_order_id;

  return v_order_id;
end;
$$;

comment on function public.confirm_extraction_draft is
  'Turns a reviewed extraction draft into a real inbound order: the order, its lines, its first status_history row and the draft being marked consumed, all in one transaction. SECURITY INVOKER: RLS still applies. Refuses a draft whose confirmed_at is already set, and a draft with nothing extracted.';


-- ===========================================================================
-- 3. GRANTS, EXPLICIT AND WITHOUT PUBLIC
-- ===========================================================================

grant execute on function public.confirm_extraction_draft(
  uuid, text, text, public.currency_code, date, date, numeric, jsonb
) to authenticated;

grant execute on function public.confirm_extraction_draft(
  uuid, text, text, public.currency_code, date, date, numeric, jsonb
) to service_role;

-- What exists now.
revoke execute on all functions in schema public from public;

-- And what stops it recurring at 0012.
alter default privileges for role postgres in schema public
  revoke execute on functions from public;

commit;


-- ===========================================================================
-- VERIFICATION
-- ===========================================================================
-- Runs after COMMIT.
--
-- Expect: anon_can_execute false on every row, authenticated_can_execute true
-- on every function the application calls, and set_updated_at false, which is
-- correct because it is only ever reached through a trigger.

select
  p.proname,
  has_function_privilege('anon',          p.oid, 'EXECUTE') as anon_can_execute,
  has_function_privilege('authenticated', p.oid, 'EXECUTE') as authenticated_can_execute,
  has_function_privilege('service_role',  p.oid, 'EXECUTE') as service_role_can_execute
from pg_proc p
join pg_namespace n on n.oid = p.pronamespace
where n.nspname = 'public'
order by p.proname;

-- And the corrected constraint, so its expression is in the journal.
select conname, pg_get_constraintdef(oid) as definition
from pg_constraint
where conrelid = 'public.extraction_drafts'::regclass
  and conname = 'extraction_drafts_confirmed_pair';
$mig$])
on conflict (version) do nothing
returning version, name;

-- Phase 2, apply. 0012, manager_flagged_products, 5398 characters of SQL.
insert into supabase_migrations.schema_migrations (version, name, statements)
values ('0012', 'manager_flagged_products', array[$mig$-- 0012_manager_flagged_products.sql
-- RC Inventory phase 2, card P2-18. The account_manager may create a product
-- only through the extraction confirm path, and only flagged.
--
-- Applied by EXECUTOR under ruling R-012. Runs as one transaction.
-- Contains no DROP TABLE, no TRUNCATE and no DELETE.
--
-- ONE NEAR-MISS, NAMED RATHER THAN BURIED, as ruling R-031 requires. This file
-- contains a `DROP POLICY`:
--
--     drop policy products_insert on public.products;
--
-- It removes a rule about rows and no row. R-031 widened CLAUDE.md 8.6 to the
-- operations that destroy rows and this is not one of them; the three
-- conditions it attaches are met: the statement is quoted verbatim in the
-- report, the file is parsed with pgsql-parser before it goes near the
-- database, and the apply is journalled with this near-miss named. A policy is
-- REPLACED, never edited, so there is no other way to change one.
--
-- ===========================================================================
-- WHAT WAS BROKEN
-- ===========================================================================
--
-- products_insert, from migration 0001, checks is_owner(). So an account_manager
-- confirming a document that names a product the catalogue does not have is
-- refused, in Romanian, at the moment of confirm.
--
-- The account_manager is the operator who uploads supplier documents every day.
-- The extraction lane exists to save that person typing, and it stopped working
-- the first time a supplier sent something new, which is the most ordinary thing
-- a supplier does. Ruling R-032.
--
-- ===========================================================================
-- WHY THE GRANT IS NARROW, AND WHAT MAKES IT CHECKABLE
-- ===========================================================================
--
-- The grant is NOT "an account_manager may create products". It is "an
-- account_manager may create a FLAGGED product", and the difference has to be
-- something the DATABASE can see rather than something the application
-- promises. An application-level check is a check the next screen can forget; a
-- policy is enforced wherever the write comes from.
--
-- needs_review IS THAT DIFFERENCE, and it is not a new column invented for this:
-- migration 0001 created it for exactly this purpose and its comment says so.
--
--   A product created at CONFIRM carries needs_review = true. It is anchored to
--   a document that was uploaded, fired, extracted and reviewed, and it arrives
--   visibly unfinished, waiting for the owner to complete it.
--
--   A product created from the CATALOGUE screen carries needs_review = false,
--   because the owner filling that form IS the review.
--
-- So: an owner may insert any product. Anyone else may insert only a flagged
-- one. That is one WITH CHECK clause and it needs no new column, no new role and
-- no new table.
--
-- WHAT KEEPS THE GRANT FROM BEING UNLIMITED CREATION: products_update still
-- checks is_owner(), untouched by this file. An account_manager cannot clear
-- needs_review, because clearing it is the act of accepting the product into the
-- catalogue, and that is the owner's. Every row that role creates therefore
-- stays visibly unfinished until an owner looks at it.
--
-- IF A LATER CHANGE EVER MAKES needs_review EDITABLE BY AN ACCOUNT_MANAGER,
-- THIS GRANT BECOMES UNLIMITED CREATION AND MUST BE RE-RULED. Written here
-- because the person making that change will be reading products_update, not
-- this file.

begin;

-- ===========================================================================
-- 1. THE INSERT POLICY, REPLACED
-- ===========================================================================

drop policy products_insert on public.products;

create policy products_insert on public.products
  for insert to authenticated
  with check (
    -- The owner, unchanged: any product, flagged or not.
    public.is_owner()
    -- Anyone else: only a flagged one. This is the extraction confirm path and
    -- nothing else reaches it, because no other screen writes needs_review true.
    or needs_review = true
  );

comment on column public.products.needs_review is
  'Set by P2-09 when an extraction names a product the catalogue does not have. Since P2-18 it is also the PRIVILEGE BOUNDARY: products_insert lets a non-owner insert a product only when this is true, so every row an account_manager creates is visibly unfinished and waiting for the owner. products_update stays owner-only, so that role cannot clear it. Making this column editable by an account_manager would turn a narrow grant into unlimited creation.';

commit;


-- ===========================================================================
-- VERIFICATION
-- ===========================================================================
-- Runs after COMMIT. The policy definitions are the database-level proof of
-- the rule and belong in the apply journal verbatim.
--
-- Expect three policies on public.products: select to authenticated using true,
-- insert with the two-branch check below, update still owner-only. And no
-- delete policy at all, which is unchanged: products are deactivated, never
-- removed.

select
  policyname,
  cmd,
  roles,
  qual        as using_expression,
  with_check  as with_check_expression
from pg_policies
where schemaname = 'public' and tablename = 'products'
order by policyname;
$mig$])
on conflict (version) do nothing
returning version, name;

-- Phase 3, post-check. What the ledger holds AFTER the three inserts, still
-- inside the open transaction. Expect twelve rows, 0001 through 0012.
select version, name from supabase_migrations.schema_migrations order by version;
select count(*) as ledger_rows_after from supabase_migrations.schema_migrations;

-- Nothing is committed yet. Send COMMIT; to keep it, or ROLLBACK; to discard it.
